### ISSUE TITLE
Making inventories where you can put items into a slot and can take out

### ISSUE THREAD

**Issue by Sytm** [MinusKube/SmartInvs#34]
Currently I am working on a market system and I tried to to something likes this: You do something to open a inventory. In this inventory you can select the amount of money you want for the items. On ther other side you can put the items in. Problem is: I can't put stuff in, event when I use this:
```java
ClickableItem.of(STACK, event -> event.setCancelled(false));
```
It just wouldn't work, so I decided to have a look into the event handling and got the idea to override the result of the event manually in one of my listener classes. Everything seemed fine when its about detecting the correct slots. BUT If I tried to put/take Items out of that area the just bugged out and graphical glitches were all over the place. So would it be possible to change some stuff to make it possible to go around this piece of code?
```java
if (e.getAction() == InventoryAction.COLLECT_TO_CURSOR
		|| e.getAction() == InventoryAction.MOVE_TO_OTHER_INVENTORY
		|| e.getAction() == InventoryAction.NOTHING) {
	e.setCancelled(true);
	return;
}
```
(Its from InventoryManager.InvListener the method onInventoryClick() )

**Comment by MinusKube** [comment]
This piece of code is a security to disallow people from removing the items using Shift + Clicks, Keyboard numbers, etc...

To allow people from putting items in an inventory, this would need some tricking, since the inventory system in Minecraft is weirdly handled. I'll try it when I have time, but if you manage to do it, a PR would be much appreciated :)

**Comment by JExcellence** [comment]
Do we have a chance to get the 1.3 Version over maven as dependency still?
