### ISSUE TITLE
Add optional open/show permissions to ClickableItem

### ISSUE THREAD

**Issue by crysis992** [MinusKube/SmartInvs#39]
Suggestion for the upcoming 1.3 version:

Add a optional constructor to ClickableItem that accepts two Strings. A permission to view the clickable Item and a permission to click the clickable item. What these permissions do is basically self-explanatory.
Don't show the item if the player is missing the required permission and don't let the player click the item if its missing.

This makes it easier to handle the content and reduces the init method alot.

**Comment by MinusKube** [comment]
Yeah that's a great idea, but I think we could make something evene more generic by accepting two `BooleanSupplier`s instead of `String`s.

This would allow to check for permissions:
```java
ClickableItem.from(...)
        .canSee(() -> player.hasPermission("my.permission"))
        .canClick(() -> player.hasPermission("my.other.permission"));
```

But also to check for anything else, like this for example:
```java
ClickableItem.from(...)
        .canSee(() -> player.getHealth() >= 10)
        .canClick(() -> player.isOp());
```

(`canSee` and `canClick` would return `true` by default)
